package com.qf.utils;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Date;

public class PrimaryKeyTest {
    public static void main(String[] args) throws Exception {

        String sql = "insert into user (u_name, u_password, u_email) values(?, ?, ?)";

        Connection conn = DbUtils.getConnection();

        /**
         * prepareStatement(String sql, int autoGeneratedKeys) 该方法的作用
         *  针对特定的数据库(例如：mysql sqlserver), 这些数据可以控制主键自增长，但是我们
         *  在代码层面需要去获取主键。
         */
        PreparedStatement ps = conn.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS);
        ps.setObject(1, "zhangsan");
        ps.setObject(2, "zhangsan");
        ps.setObject(3, "zhangsan");

        ps.executeUpdate();  //执行插入

        ResultSet rs =  ps.getGeneratedKeys();
        rs.next();
        System.out.println(rs.getInt(1));

        DbUtils.colse(rs, ps, conn);

    }
}
